<a href="https://colab.research.google.com/github/AakashAhuja30/Pytorch/blob/main/Pytorch_Tensors_Complete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import torch

In [94]:
device='cuda' if torch.cuda.is_available() else 'cpu'

In [4]:
device

'cuda'

In [7]:
#List- Can also setup dtype and also device, requires_grad
my_tensor = torch.tensor([
                          [1,2,3],
                          [4,5,6]],
            dtype = torch.float32,
            device=device, requires_grad = True    
)

In [9]:
print(my_tensor)
print(my_tensor.device)
print(my_tensor.dtype)
print(my_tensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
cuda:0
torch.float32
torch.Size([2, 3])


In [27]:
#Initialization methods
x = torch.empty((3,3)).uniform_(0,1)
print(x)
x= torch.rand((3,3))
print(x)
x = torch.zeros((2,3))
print(x)

x = torch.ones((2,2))
print(x)

x = torch.eye(2,1)
print(x)

x=torch.diag(torch.ones(5))
print(x)

x=torch.arange(start=0, end=10, step = 1)
print(x)

x=torch.linspace(start=1,end=20, steps=4)
print(x)


tensor([[0.0772, 0.4453, 0.1348],
        [0.9761, 0.7593, 0.1860],
        [0.4632, 0.3396, 0.6318]])
tensor([[0.6870, 0.4426, 0.8267],
        [0.3412, 0.5601, 0.7012],
        [0.9803, 0.5565, 0.9932]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1.],
        [0.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1.0000,  7.3333, 13.6667, 20.0000])


In [29]:
#Convert tensors between various datatypes
my_tensor = torch.arange(4)
print(my_tensor)

print(my_tensor.bool())
print(my_tensor.short())
print(my_tensor.long())
print(my_tensor.float())
print(my_tensor.double())

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [33]:
#Conversion of arrays to tensors and vice versa
import numpy as np
x=np.array([0.2,0.5,0.8])
print(x)
tensor=torch.from_numpy(x)
print(tensor)
x_np = tensor.numpy()
print(x_np)

[0.2 0.5 0.8]
tensor([0.2000, 0.5000, 0.8000], dtype=torch.float64)
[0.2 0.5 0.8]


In [52]:
#Tensor Math & Comarison Operations
x= torch.tensor([1,2,3])
y= torch.tensor([5,6,7])

#Add
z = x + y
print(z)

#Subtract
z= y-x
print(z)
#Divide- litle clunky
z= torch.divide(x,y)
print(z)
#Inplace operations += does inplace and = x=t does not do
t=2
t /=x
print(t)
#Exponentitation
z=x**2
print(z)
#Simple comparison
z=x>2
print(x[x>2])


#Matrix Multiplication
m1= torch.rand((3,2))
print(m1)
m2= torch.rand((2,1))
print(m2)
z=torch.mm(m1,m2)
print(z)
print(z.shape)

#Dot Product
z= torch.dot(x,y)
print(z)

#batch Matrix multiplication
batch=64
n=10
m=20
p=30

tensor1 = torch.rand((batch,n,m))
tensor2 = torch.rand((batch,m,p))
z= torch.bmm(tensor1, tensor2)
print(z.shape)


tensor([ 6,  8, 10])
tensor([4, 4, 4])
tensor([0.2000, 0.3333, 0.4286])
tensor([2.0000, 1.0000, 0.6667])
tensor([1, 4, 9])
tensor([3])
tensor([[0.3664, 0.1163],
        [0.8242, 0.3704],
        [0.9662, 0.1739]])
tensor([[0.4117],
        [0.2113]])
tensor([[0.1754],
        [0.4176],
        [0.4346]])
torch.Size([3, 1])
tensor(38)
torch.Size([64, 10, 30])


In [55]:
#Broadcasting
x1= torch.ones((2,2))
print(x1)
x2= torch.ones(1,2)
print(x2)
#Broadcasting
z=x1+x2
print(z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


In [70]:
#Tensor Operations
print(x)
print(y)
print(torch.sum(x,dim=0))

val,_=torch.max(x, dim=0)
print(val)
z = torch.mean(x.float())
print(z)

z = torch.eq(x,y)
print(z)

sorted_y, indices =  torch.sort(y,descending=True)
print(sorted_y)

z=torch.clamp(y,min=5,max=6)
print(z)

z=torch.argmin(y)
print(z)


tensor([1, 2, 3])
tensor([5, 6, 7])
tensor(6)
tensor(3)
tensor(2.)
tensor([False, False, False])
tensor([7, 6, 5])
tensor([5, 6, 6])
tensor(0)


In [97]:
#Tensor Indexing
x = torch.arange(start=0,end=10,step=2)
print(x)
indices = [2,3,4]
print(x[indices])

batch_size = 10
features = 25

x = torch.rand((batch_size, features))
print(x[0].shape)

print(x[:,0].shape)
print(x[2,0:10])

x = torch.rand((3,5))
print(x)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols])

x=torch.arange(10)
print(x)
print(x[(x<2) | (x>6)])
print(x[x%2==0])

z=torch.where(x>5,x,x**2)
print(z)
print(x)

print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(torch.tensor([0,0,1,2,2,3,4]).numel())


tensor([0, 2, 4, 6, 8])
tensor([4, 6, 8])
torch.Size([25])
torch.Size([10])
tensor([0.2195, 0.7917, 0.2866, 0.2851, 0.7398, 0.1627, 0.0173, 0.1814, 0.5210,
        0.7895])
tensor([[0.5358, 0.0732, 0.5958, 0.1008, 0.6440],
        [0.7237, 0.9427, 0.4739, 0.7056, 0.0406],
        [0.9722, 0.3064, 0.9417, 0.9685, 0.1319]])
tensor([0.0406, 0.5358])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4])
7


In [110]:
#tensor reshaping
x = torch.arange(9) 

#3*3 matrix
y= x.reshape(3,3)
print(y)

#Concatenate matrices along any axis

x1= torch.rand((1,2))
print(x1)
x2= torch.rand((1,2))
print(x2)
z= torch.cat((x1,x2), dim=0)
print(z)
print(z.shape)

#flattening the matrix
z= x1.view(-1)
print(z.shape)

batch=65
x = torch.rand((batch,3,4,5))
z=x.view(batch,-1)
print(z.shape)

z= x.permute(0,2,1,3)
print(z.shape)

#Adding axes to tensor

x= torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

z=torch.arange(10).unsqueeze(0).unsqueeze(1)
print(z.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0.3384, 0.6072]])
tensor([[0.8600, 0.4918]])
tensor([[0.3384, 0.6072],
        [0.8600, 0.4918]])
torch.Size([2, 2])
torch.Size([2])
torch.Size([65, 60])
torch.Size([65, 4, 3, 5])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])
